name: Unit-Testing

on:
  push:
    branches:
      - "dev_branch11"
  pull_request:
      - "dev_branch11"


jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Node Install
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm i

      - name: Run Mocha Unit-Testing
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node-version}}
      - run: npm run test:ci